<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class AdminSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $maxOrder = DB::table('menus')->where('parent_id', null)->max('order') ?? 999;
        $adminRole = DB::table('roles')->insertGetId([
            'name_en' => 'Admin',
            'name_kh' => 'អ្នកគ្រប់គ្រង',
            'description' => 'Administrator with full access',
            'administrator' => 1,
            'order' => 1,
            'created_by' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $userRole = DB::table('roles')->insertGetId([
            'name_en' => 'User',
            'name_kh' => 'អ្នកប្រើប្រាស់',
            'description' => 'Regular user with limited access',
            'order' => 2,
            'created_by' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $adminUser = DB::table('users')->insertGetId([
            'username' => 'admin',
            'name_en' => 'Admin',
            'name_kh' => 'អ្នកគ្រប់គ្រង',
            'email' => 'test@gmail.com',
            'password' => Hash::make('123'),
            'phone' => '123456789',
            'created_by' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $regularUser = DB::table('users')->insertGetId([
            'username' => 'user',
            'name_en' => 'Regular User',
            'name_kh' => 'អ្នកប្រើប្រាស់ធម្មតា',
            'email' => 'user@wintech.com.kh',
            'password' => Hash::make('password'),
            'phone' => '987654321',
            'created_by' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('user_role')->insert([
            ['user_id' => $adminUser, 'role_id' => $adminRole],
            ['user_id' => $regularUser, 'role_id' => $userRole],
        ]);
        $dashboard = DB::table('menus')->insertGetId([
            'name_en' => 'Dashboard',
            'name_kh' => 'ផ្ទារគ្រប់គ្រង',
            'icon' => 'ph ph-house',
            'order' => 1,
            'url' => '/dashboard',
            'created_by' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $settingsMenu = DB::table('menus')->insertGetId([
            'name_en' => 'Settings',
            'name_kh' => 'ការកំណត់',
            'icon' => 'ph ph-sliders',
            'order' => $maxOrder + 1,
            'url' => '',
            'parent_id' => null,
            'created_by' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $usersManagement = DB::table('menus')->insertGetId([
            'name_en' => 'Users Management',
            'name_kh' => 'ការគ្រប់គ្រងអ្នកប្រើប្រាស់',
            'icon' => 'ph ph-user-gear',
            'order' => 2,
            'url' => '',
            'parent_id' => null,
            'created_by' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $users = DB::table('menus')->insertGetId([
            'name_en' => 'Users',
            'name_kh' => 'អ្នកប្រើប្រាស់',
            'icon' => 'ph ph-user-circle-dashed',
            'order' => 1,
            'url' => 'settings/users-management/users',
            'parent_id' => $usersManagement,
            'created_by' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $roles = DB::table('menus')->insertGetId([
            'name_en' => 'Roles',
            'name_kh' => 'តួនាទី',
            'icon' => 'ph ph-person-simple-circle',
            'order' => 2,
            'url' => 'settings/users-management/roles',
            'parent_id' => $usersManagement,
            'created_by' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        // $dbmockup = DB::table('menus')->insertGetId([
        //     'name_en' => 'DB Mockup',
        //     'name_kh' => 'គម្រោង',
        //     'icon' => 'ph ph-paypal-logo',
        //     'order' => 3,
        //     'url' => 'payment-ui',
        //     'created_by' => 1,
        //     'created_at' => now(),
        //     'updated_at' => now(),
        // ]);
        // $project = DB::table('menus')->insertGetId([
        //     'name_en' => 'Project',
        //     'name_kh' => 'គម្រោង',
        //     'icon' => 'ph ph-student',
        //     'order' => 1,
        //     'url' => 'dbmockup/projects',
        //     'parent_id' => $dbmockup,
        //     'created_by' => 1,
        //     'created_at' => now(),
        //     'updated_at' => now(),
        // ]);
        // $endpoint = DB::table('menus')->insertGetId([
        //     'name_en' => 'Endpoint',
        //     'name_kh' => 'ចំណុចបញ្ចប់',
        //     'icon' => 'ph ph-student',
        //     'order' => 1,
        //     'url' => 'dbmockup/endpoint',
        //     'parent_id' => $dbmockup,
        //     'created_by' => 1,
        //     'created_at' => now(),
        //     'updated_at' => now(),
        // ]);

        $product = DB::table('menus')->insertGetId([
            'name_en' => 'Product',
            'name_kh' => 'ផលិតផល',
            'icon' => 'ph ph-package', // Main product icon
            'order' => 3,
            'url' => 'payment-ui',
            'created_by' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        $view_product = DB::table('menus')->insertGetId([
            'name_en' => 'View Product',
            'name_kh' => 'មើល ផលិតផល',
            'icon' => 'ph ph-eye', // View/see icon
            'order' => 1,
            'url' => 'product/products',
            'parent_id' => $product,
            'created_by' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ]);


        $categories = DB::table('menus')->insertGetId([
            'name_en' => 'Categories',
            'name_kh' => 'ប្រភេទ', // Added Khmer translation
            'icon' => 'ph ph-tag-simple', // Category/tag icon
            'order' => 4, // Changed to 2 to maintain order
            'url' => 'product/categories',
            'parent_id' => $product,
            'created_by' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        $sales = DB::table('menus')->insertGetId([
            'name_en' => 'Sales',
            'name_kh' => 'ការលក់',
            'icon' => 'ph ph-package',
            'order' => 5,
            'created_by' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $pos_sale = DB::table('menus')->insertGetId([
            'name_en' => 'Pos sale',
            'name_kh' => 'ចំណុចលក់',
            'icon' => 'ph ph-tag-simple',
            'order' => 1,
            'url' => 'sales',
            'parent_id' => $sales,
            'created_by' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $Stock_count = DB::table('menus')->insertGetId([
            'name_en' => 'Stock Count',
            'name_kh' => 'ស្តុក',
            'icon' => 'ph ph-tag-simple',
            
            'order' => 2,
            'url' => 'sales/stockcount/index',
            'parent_id' => $sales,
            'created_by' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        $reports = DB::table('menus')->insertGetId([
            'name_en' => 'Report',
            'name_kh' => 'របាយការណ៍',
            'icon' => 'ph ph-tag-simple',
            'order' => 12,
            'created_by' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $product_sale_report = DB::table('menus')->insertGetId([
            'name_en' => 'Product Sale Report',
            'name_kh' => 'របាយការណ៍ លក់ផលិផល',
            'icon' => '',
            'order' => 1,
            'url' => 'reports/product-sales-report',
            'parent_id' => $reports,
            'created_by' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ]);


        $units = DB::table('menus')->insertGetId([
            'name_en' => 'Units',
            'name_kh' => 'ខ្នាត',
            'icon' => 'ph ph-resize', // or 'ph ph-ruler' for measurement
            'order' => 7,
            'url' => 'setting/units',
            'parent_id' => $settingsMenu,
            'created_by' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        $base_units = DB::table('menus')->insertGetId([
            'name_en' => 'Base Units',
            'name_kh' => 'ឯកតាមូលដ្ឋាន',
            'icon' => 'ph ph-ruler', // or 'ph ph-ruler' for measurement
            'order' => 1,
            'url' => 'setting/base-units',
            'parent_id' => $settingsMenu,
            'created_by' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $unit_convert = DB::table('menus')->insertGetId([
            'name_en' => 'Convert Unit',
            'name_kh' => 'ការបម្លែងឯកតា',
            'icon' => 'ph ph-ruler',
            'order' => 2,
            'url' => 'setting/unit_convert',
            'parent_id' => $settingsMenu,
            'created_by' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ]);


        $floor = DB::table('menus')->insertGetId([
            'name_en' => 'Floor',
            'name_kh' => 'ជាន់',
            'icon' => 'ph ph-stack-simple', // or 'ph ph-buildings'
            'order' => 2,
            'url' => 'setting/floor',
            'parent_id' => $settingsMenu,
            'created_by' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        $room = DB::table('menus')->insertGetId([
            'name_en' => 'Room',
            'name_kh' => 'បន្ទប់',
            'icon' => 'ph ph-door', // or 'ph ph-square-four'
            'order' => 3,
            'url' => 'setting/room',
            'parent_id' => $settingsMenu,
            'created_by' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $people = DB::table('menus')->insertGetId([
            'name_en' => 'People',
            'name_kh' => 'មនុស្ស', // Added Khmer translation
            'icon' => 'ph ph-users', // Multiple people icon
            'order' => 8,
            'url' => 'people/suppliers',
            'created_by' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        $suppliers = DB::table('menus')->insertGetId([
            'name_en' => 'Suppliers',
            'name_kh' => 'អ្នកផ្គត់ផ្គង់',
            'icon' => 'ph ph-truck', // Delivery/supply icon
            'order' => 1,
            'url' => 'people/suppliers',
            'parent_id' => $people,
            'created_by' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $customer = DB::table('menus')->insertGetId([
            'name_en' => 'Customer',
            'name_kh' => 'អតិថិជន',
            'icon' => 'ph ph-user-circle', // Single customer icon (matches your preferred style)
            'order' => 2, // Changed to 2 to maintain order
            'url' => 'people/customer',
            'parent_id' => $people,
            'created_by' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $group_customer = DB::table('menus')->insertGetId([
            'name_en' => 'Group Customer',
            'name_kh' => 'ក្រុម អតិថិជន',
            'icon' => 'ph ph-users-three', // Group of customers
            'order' => 3, // Adjusted order sequence
            'url' => 'people/group_customer',
            'parent_id' => $people,
            'created_by' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        $group_saleman = DB::table('menus')->insertGetId([
            'name_en' => 'Group Salesman',
            'name_kh' => 'ក្រុម អ្នកលក់',
            'icon' => 'ph ph-briefcase', // Standard briefcase icon (exists)
            'order' => 5,
            'url' => 'people/group_saleman',
            'parent_id' => $people,
            'created_by' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $saleman = DB::table('menus')->insertGetId([
            'name_en' => 'Salesman',
            'name_kh' => 'អ្នកលក់',
            'icon' => 'ph ph-briefcase', // Standard briefcase icon (exists)
            'order' => 4,
            'url' => 'people/saleman',
            'parent_id' => $people,
            'created_by' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $menubox = DB::table('menus')->insertGetId([
            'name_en' => 'Menu Box',
            'name_kh' => 'ប្រអប់ម៉ឺនុយ',
            'icon' => 'ph ph-cube',
            'order' => 9,
            'url' => 'menu_box',
            'parent_id' => null,
            'created_by' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $menubox_items = DB::table('menus')->insertGetId([
            'name_en' => 'Menu Box Items',
            'name_kh' => 'អត្ថបទប្រអប់ម៉ឺនុយ',
            'icon' => 'ph ph-square-half-bottom',
            'order' => 1,
            'url' => 'menu_box',
            'parent_id' => $menubox,
            'created_by' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $slidebox = DB::table('menus')->insertGetId([
            'name_en' => 'Slide Box',
            'name_kh' => 'ស្លាយ',
            'icon' => 'ph ph-sidebar',
            'order' => 1,
            'url' => 'menu_box/slidebox',
            'parent_id' => $menubox,
            'created_by' => 2,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $booking = DB::table('menus')->insertGetId([
            'name_en' => 'Booking',
            'name_kh' => 'កក់​ទុក',
            'icon' => 'ph ph-chat-centered-text',
            'order' => 10,
            'url' => 'menu_box/booking',
            'parent_id' => $menubox,
            'created_by' => 2,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $other = DB::table('menus')->insertGetId([
            'name_en' => 'Other',
            'name_kh' => 'ដទៃទៀត',
            'icon' => 'ph ph-gear',
            'order' => 11,
            'url' => 'other/cash_accounts',
            'parent_id' => null,
            'created_by' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $cash_account = DB::table('menus')->insertGetId([
            'name_en' => 'Cash Account',
            'name_kh' => 'គណនី​ ប្រាក់​',
            'icon' => 'ph ph-bank',
            'order' => 1,
            'url' => 'other/cash_accounts',
            'parent_id' => $other,
            'created_by' => 2,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $branch = DB::table('menus')->insertGetId([
            'name_en' => 'Branch',
            'name_kh' => 'សាខា​',
            'icon' => 'ph ph-warehouse',
            'order' => 2,
            'url' => 'other/branch',
            'parent_id' => $other,
            'created_by' => 2,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $warehouses = DB::table('menus')->insertGetId([
            'name_en' => 'Warehouses',
            'name_kh' => 'ឃ្លាំង',
            'icon' => 'ph ph-warehouse',
            'order' => 3,
            'url' => 'other/warehouses',
            'parent_id' => $other,
            'created_by' => 2,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $currencies = DB::table('menus')->insertGetId([
            'name_en' => 'Currencies',
            'name_kh' => 'រូបិយប័ណ្ណ',
            'icon' => 'ph ph-currency-circle-dollar',
            'order' => 3,
            'url' => 'other/currencies',
            'parent_id' => $other,
            'created_by' => 2,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $interview = DB::table('menus')->insertGetId([
            'name_en' => 'Interview',
            'name_kh' => 'សម្ភាស',
            'icon' => 'ph ph-users-four',
            'order' => 9,
            'url' => 'interview',
            'parent_id' => null,
            'created_by' => 8,
            'created_at' => now(),
            'updated_at' => now(),
        ]);


        $customer_deposit = DB::table('menus')->insertGetId([
            'name_en' => 'Customer Deposit',
            'name_kh' => 'អតិថិជន​ ដាក់ប្រាក់​',
            'icon' => 'ph ph-hand-deposit',
            'order' => 1,
            'url' => 'people/customer_deposit',
            'parent_id' => $people,
            'created_by' => 2,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $expense = DB::table('menus')->insertGetId([
            'name_en' => 'Expense',
            'name_kh' => 'ចំណាយ',
            'icon' => 'ph ph-money',
            'order' => 1,
            'url' => 'expense',
            'created_by' => 2,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $expense_category = DB::table('menus')->insertGetId([
            'name_en' => 'Expense Category',
            'name_kh' => 'ប្រភេទចំណាយ​',
            'icon' => 'ph ph-money',
            'order' => 1,
            'url' => 'expense/expense_category',
            'parent_id' => $expense,
            'created_by' => 2,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $add_expense = DB::table('menus')->insertGetId([
            'name_en' => 'Add Expense',
            'name_kh' => 'បញ្ចូលចំណាយ​',
            'icon' => 'ph ph-money',
            'order' => 1,
            'url' => 'expense/add_expense',
            'parent_id' => $expense,
            'created_by' => 2,
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        $adjustment = DB::table('menus')->insertGetId([
            'name_en' => 'Adjustment',
            'name_kh' => 'ស្តុក',
            'icon' => 'ph ph-warehouse',
            'order' => 6,
            'url' => 'adjustment',
            'created_by' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $purchases = DB::table('menus')->insertGetId([
            'name_en' => 'Purchases',
            'name_kh' => 'ការបញ្ចារទិញ',
            'icon' => 'ph ph-warehouse',
            'order' => 6,
            'url' => 'purchases',
            'created_by' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ]);



        $permissions = [
            [
                'name_en' => 'List',
                'name_kh' => 'បញ្ជី',
                'slug' => 'dashboard',
                'menu_id' => $dashboard,
                'is_menu' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'List',
                'name_kh' => 'បញ្ជី',
                'slug' => 'settings.users-management.users.index',
                'menu_id' => $users,
                'is_menu' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Add',
                'name_kh' => 'បន្ថែម',
                'slug' => 'settings.users-management.users.add',
                'menu_id' => $users,
                'is_menu' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Edit',
                'name_kh' => 'កែប្រែ',
                'slug' => 'settings.users-management.users.edit',
                'menu_id' => $users,
                'is_menu' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Delete',
                'name_kh' => 'លុប',
                'slug' => 'settings.users-management.users.delete',
                'menu_id' => $users,
                'is_menu' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Permission',
                'name_kh' => 'សិទ្ធិ',
                'slug' => 'settings.users-management.users.permission',
                'menu_id' => $users,
                'is_menu' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'List',
                'name_kh' => 'បញ្ជី',
                'slug' => 'settings.users-management.roles.index',
                'menu_id' => $roles,
                'is_menu' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Add',
                'name_kh' => 'បង្កើត',
                'slug' => 'settings.users-management.roles.add',
                'menu_id' => $roles,
                'is_menu' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Edit',
                'name_kh' => 'កែប្រែ',
                'slug' => 'settings.users-management.roles.edit',
                'menu_id' => $roles,
                'is_menu' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Delete',
                'name_kh' => 'លុប',
                'slug' => 'settings.users-management.roles.delete',
                'menu_id' => $roles,
                'is_menu' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // [
            //     'name_en' => 'List',
            //     'name_kh' => 'បញ្ជី',
            //     'slug' => 'dbmockup.projects.index',
            //     'menu_id' => $project,
            //     'is_menu' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name_en' => 'Add',
            //     'name_kh' => 'បង្កើត',
            //     'slug' => 'dbmockup.projects.add',
            //     'menu_id' => $project,
            //     'is_menu' => 0,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name_en' => 'Edit',
            //     'name_kh' => 'កែប្រែ',
            //     'slug' => 'dbmockup.projects.edit',
            //     'menu_id' => $project,
            //     'is_menu' => 0,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name_en' => 'Delete',
            //     'name_kh' => 'លុប',
            //     'slug' => 'dbmockup.projects.delete',
            //     'menu_id' => $project,
            //     'is_menu' => 0,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name_en' => 'List',
            //     'name_kh' => 'បញ្ជី',
            //     'slug' => 'dbmockup.endpoint.index',
            //     'menu_id' => $endpoint,
            //     'is_menu' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name_en' => 'Add',
            //     'name_kh' => 'បង្កើត',
            //     'slug' => 'dbmockup.endpoint.add',
            //     'menu_id' => $endpoint,
            //     'is_menu' => 0,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name_en' => 'Edit',
            //     'name_kh' => 'កែប្រែ',
            //     'slug' => 'dbmockup.endpoint.edit',
            //     'menu_id' => $endpoint,
            //     'is_menu' => 0,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name_en' => 'Delete',
            //     'name_kh' => 'លុប',
            //     'slug' => 'dbmockup.endpoint.delete',
            //     'menu_id' => $endpoint,
            //     'is_menu' => 0,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            [
                'name_en' => 'List',
                'name_kh' => 'បញ្ជី',
                'slug' => 'product.products.index',
                'menu_id' => $view_product,
                'is_menu' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Add',
                'name_kh' => 'បង្កើត',
                'slug' => 'product.products.add',
                'menu_id' => $view_product,
                'is_menu' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Edit',
                'name_kh' => 'កែប្រែ',
                'slug' => 'product.products.edit',
                'menu_id' => $view_product,
                'is_menu' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Delete',
                'name_kh' => 'លុប',
                'slug' => 'product.products.delete',
                'menu_id' => $view_product,
                'is_menu' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'List',
                'name_kh' => 'បញ្ជី',
                'slug' => 'product.categories.index',
                'menu_id' => $categories,
                'is_menu' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Add',
                'name_kh' => 'បង្កើត',
                'slug' => 'product.categories.add',
                'menu_id' => $categories,
                'is_menu' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Edit',
                'name_kh' => 'កែប្រែ',
                'slug' => 'product.categories.edit',
                'menu_id' => $categories,
                'is_menu' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Delete',
                'name_kh' => 'លុប',
                'slug' => 'product.categories.delete',
                'menu_id' => $categories,
                'is_menu' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'List',
                'name_kh' => 'បញ្ជី',
                'slug' => 'setting.units.index',
                'menu_id' => $units,
                'is_menu' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Add',
                'name_kh' => 'បង្កើត',
                'slug' => 'setting.units.add',
                'menu_id' => $units,
                'is_menu' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Edit',
                'name_kh' => 'កែប្រែ',
                'slug' => 'setting.units.edit',
                'menu_id' => $units,
                'is_menu' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Delete',
                'name_kh' => 'លុប',
                'slug' => 'setting.units.delete',
                'menu_id' => $units,
                'is_menu' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'List',
                'name_kh' => 'បញ្ជី',
                'slug' => 'setting.floor.index',
                'menu_id' => $floor,
                'is_menu' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Add',
                'name_kh' => 'បង្កើត',
                'slug' => 'setting.floor.add',
                'menu_id' => $floor,
                'is_menu' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Edit',
                'name_kh' => 'កែប្រែ',
                'slug' => 'setting.floor.edit',
                'menu_id' => $floor,
                'is_menu' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Delete',
                'name_kh' => 'លុប',
                'slug' => 'setting.floor.delete',
                'menu_id' => $floor,
                'is_menu' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'List',
                'name_kh' => 'បញ្ជី',
                'slug' => 'setting.room.index',
                'menu_id' => $room,
                'is_menu' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Add',
                'name_kh' => 'បង្កើត',
                'slug' => 'setting.room.add',
                'menu_id' => $room,
                'is_menu' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Edit',
                'name_kh' => 'កែប្រែ',
                'slug' => 'setting.room.edit',
                'menu_id' => $room,
                'is_menu' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Delete',
                'name_kh' => 'លុប',
                'slug' => 'setting.room.delete',
                'menu_id' => $room,
                'is_menu' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            //suppliers
            [
                'name_en' => 'List',
                'name_kh' => 'បញ្ជី',
                'slug' => 'people.suppliers.index',
                'menu_id' => $suppliers,
                'is_menu' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Add',
                'name_kh' => 'បង្កើត',
                'slug' => 'people.suppliers.add',
                'menu_id' => $suppliers,
                'is_menu' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Edit',
                'name_kh' => 'កែប្រែ',
                'slug' => 'people.suppliers.edit',
                'menu_id' => $suppliers,
                'is_menu' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Delete',
                'name_kh' => 'លុប',
                'slug' => 'people.suppliers.delete',
                'menu_id' => $suppliers,
                'is_menu' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            //customer
            [
                'name_en' => 'List',
                'name_kh' => 'បញ្ជី',
                'slug' => 'people.customer.index',
                'menu_id' => $customer,
                'is_menu' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Add',
                'name_kh' => 'បង្កើត',
                'slug' => 'people.customer.add',
                'menu_id' => $customer,
                'is_menu' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Edit',
                'name_kh' => 'កែប្រែ',
                'slug' => 'people.customer.edit',
                'menu_id' => $customer,
                'is_menu' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Delete',
                'name_kh' => 'លុប',
                'slug' => 'people.customer.delete',
                'menu_id' => $customer,
                'is_menu' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'List',
                'name_kh' => 'បញ្ជី',
                'slug' => 'people.group_customer.index',
                'menu_id' => $group_customer,
                'is_menu' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Add',
                'name_kh' => 'បង្កើត',
                'slug' => 'people.group_customer.add',
                'menu_id' => $group_customer,
                'is_menu' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Edit',
                'name_kh' => 'កែប្រែ',
                'slug' => 'people.group_customer.edit',
                'menu_id' => $group_customer,
                'is_menu' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Delete',
                'name_kh' => 'លុប',
                'slug' => 'people.group_customer.delete',
                'menu_id' => $group_customer,
                'is_menu' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'List',
                'name_kh' => 'បញ្ជី',
                'slug' => 'people.group_saleman.index',
                'menu_id' => $group_saleman,
                'is_menu' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Add',
                'name_kh' => 'បង្កើត',
                'slug' => 'people.group_saleman.add',
                'menu_id' => $group_saleman,
                'is_menu' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Edit',
                'name_kh' => 'កែប្រែ',
                'slug' => 'people.group_saleman.edit',
                'menu_id' => $group_saleman,
                'is_menu' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Delete',
                'name_kh' => 'លុប',
                'slug' => 'people.group_saleman.delete',
                'menu_id' => $group_saleman,
                'is_menu' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'List',
                'name_kh' => 'បញ្ជី',
                'slug' => 'people.saleman.index',
                'menu_id' => $saleman,
                'is_menu' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Add',
                'name_kh' => 'បង្កើត',
                'slug' => 'people.saleman.add',
                'menu_id' => $saleman,
                'is_menu' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Edit',
                'name_kh' => 'កែប្រែ',
                'slug' => 'people.saleman.edit',
                'menu_id' => $saleman,
                'is_menu' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Delete',
                'name_kh' => 'លុប',
                'slug' => 'people.saleman.delete',
                'menu_id' => $saleman,
                'is_menu' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name_en' => 'List',
                'name_kh' => 'បញ្ជី',
                'slug' => 'menu_box.booking.index',
                'menu_id' => $booking,
                'is_menu' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Add',
                'name_kh' => 'បង្កើត',
                'slug' => 'menu_box.booking.add',
                'menu_id' => $booking,
                'is_menu' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Edit',
                'name_kh' => 'កែប្រែ',
                'slug' => 'menu_box.booking.edit',
                'menu_id' => $booking,
                'is_menu' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Delete',
                'name_kh' => 'លុប',
                'slug' => 'menu_box.booking.delete',
                'menu_id' => $booking,
                'is_menu' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name_en' => 'List',
                'name_kh' => 'បញ្ជី',
                'slug' => 'other.cash_accounts.index',
                'menu_id' => $cash_account,
                'is_menu' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Add',
                'name_kh' => 'បង្កើត',
                'slug' => 'other.cash_accounts.add',
                'menu_id' => $cash_account,
                'is_menu' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Edit',
                'name_kh' => 'កែប្រែ',
                'slug' => 'other.cash_accounts.edit',
                'menu_id' => $cash_account,
                'is_menu' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Delete',
                'name_kh' => 'លុប',
                'slug' => 'other.cash_accounts.delete',
                'menu_id' => $cash_account,
                'is_menu' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name_en' => 'List',
                'name_kh' => 'បញ្ជី',
                'slug' => 'other.branch.index',
                'menu_id' => $branch,
                'is_menu' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Add',
                'name_kh' => 'បង្កើត',
                'slug' => 'other.branch.add',
                'menu_id' => $branch,
                'is_menu' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Edit',
                'name_kh' => 'កែប្រែ',
                'slug' => 'other.branch.edit',
                'menu_id' => $branch,
                'is_menu' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Delete',
                'name_kh' => 'លុប',
                'slug' => 'other.branch.delete',
                'menu_id' => $branch,
                'is_menu' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name_en' => 'List',
                'name_kh' => 'បញ្ជី',
                'slug' => 'other.warehouses.index',
                'menu_id' => $warehouses,
                'is_menu' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Add',
                'name_kh' => 'បង្កើត',
                'slug' => 'other.warehouses.add',
                'menu_id' => $warehouses,
                'is_menu' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Edit',
                'name_kh' => 'កែប្រែ',
                'slug' => 'other.warehouses.edit',
                'menu_id' => $warehouses,
                'is_menu' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Delete',
                'name_kh' => 'លុប',
                'slug' => 'other.warehouses.delete',
                'menu_id' => $warehouses,
                'is_menu' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'List',
                'name_kh' => 'បញ្ជី',
                'slug' => 'other.currencies.index',
                'menu_id' => $currencies,
                'is_menu' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Add',
                'name_kh' => 'បង្កើត',
                'slug' => 'other.currencies.add',
                'menu_id' => $currencies,
                'is_menu' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Edit',
                'name_kh' => 'កែប្រែ',
                'slug' => 'other.currencies.edit',
                'menu_id' => $currencies,
                'is_menu' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Delete',
                'name_kh' => 'លុប',
                'slug' => 'other.currencies.delete',
                'menu_id' => $currencies,
                'is_menu' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],


            [
                'name_en' => 'List',
                'name_kh' => 'បញ្ជី',
                'slug' => 'people.customer_deposit.index',
                'menu_id' => $customer_deposit,
                'is_menu' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Add',
                'name_kh' => 'បង្កើត',
                'slug' => 'people.customer_deposit.add',
                'menu_id' => $customer_deposit,
                'is_menu' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Edit',
                'name_kh' => 'កែប្រែ',
                'slug' => 'people.customer_deposit.edit',
                'menu_id' => $customer_deposit,
                'is_menu' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Delete',
                'name_kh' => 'លុប',
                'slug' => 'people.customer_deposit.delete',
                'menu_id' => $customer_deposit,
                'is_menu' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'List',
                'name_kh' => 'បញ្ជី',
                'slug' => 'expense.expense_category.index',
                'menu_id' => $expense_category,
                'is_menu' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Add',
                'name_kh' => 'បង្កើត',
                'slug' => 'expense.expense_category.add',
                'menu_id' => $expense_category,
                'is_menu' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Edit',
                'name_kh' => 'កែប្រែ',
                'slug' => 'expense.expense_category.edit',
                'menu_id' => $expense_category,
                'is_menu' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Delete',
                'name_kh' => 'លុប',
                'slug' => 'expense.expense_category.delete',
                'menu_id' => $expense_category,
                'is_menu' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name_en' => 'List',
                'name_kh' => 'បញ្ជី',
                'slug' => 'expense.add_expense.index',
                'menu_id' => $add_expense,
                'is_menu' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Add',
                'name_kh' => 'បង្កើត',
                'slug' => 'expense.add_expense.add',
                'menu_id' => $add_expense,
                'is_menu' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Edit',
                'name_kh' => 'កែប្រែ',
                'slug' => 'expense.add_expense.edit',
                'menu_id' => $add_expense,
                'is_menu' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Delete',
                'name_kh' => 'លុប',
                'slug' => 'expense.add_expense.delete',
                'menu_id' => $add_expense,
                'is_menu' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'List',
                'name_kh' => 'បញ្ជី',
                'slug' => 'interview.index',
                'menu_id' => $interview,
                'is_menu' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Add',
                'name_kh' => 'បង្កើត',
                'slug' => 'interview.add',
                'menu_id' => $interview,
                'is_menu' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Edit',
                'name_kh' => 'កែប្រែ',
                'slug' => 'interview.edit',
                'menu_id' => $interview,
                'is_menu' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Delete',
                'name_kh' => 'លុប',
                'slug' => 'interview.delete',
                'menu_id' => $interview,
                'is_menu' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'List',
                'name_kh' => 'បញ្ជី',
                'slug' => 'setting.base_units.index',
                'menu_id' => $base_units,
                'is_menu' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Add',
                'name_kh' => 'បង្កើត',
                'slug' => 'setting.base_units.add',
                'menu_id' => $base_units,
                'is_menu' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Edit',
                'name_kh' => 'កែប្រែ',
                'slug' => 'setting.base_units.edit',
                'menu_id' => $base_units,
                'is_menu' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Delete',
                'name_kh' => 'លុប',
                'slug' => 'setting.base_units.delete',
                'menu_id' => $base_units,
                'is_menu' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name_en' => 'List',
                'name_kh' => 'បញ្ជី',
                'slug' => 'setting.unit_convert.index',
                'menu_id' => $unit_convert,
                'is_menu' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Add',
                'name_kh' => 'បង្កើត',
                'slug' => 'setting.unit_convert.save',
                'menu_id' => $unit_convert,
                'is_menu' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Edit',
                'name_kh' => 'កែប្រែ',
                'slug' => 'setting.unit_convert.edit',
                'menu_id' => $unit_convert,
                'is_menu' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Delete',
                'name_kh' => 'លុប',
                'slug' => 'setting.unit_convert.delete',
                'menu_id' => $unit_convert,
                'is_menu' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ];
        DB::table('permissions')->insert($permissions);
    }
}
